Добавил второе д/з, создал workspace
MaxFerrara/FocusStartHomeworks pull request #2
Opened 2020-11-01 17:27 UTC by MaxFerrara

Привет, вопросы:
1) прога сейчас падает в некоторых случаях из-за добавления элементов в обычный массив(непотоко-безопасный) следует ли его удалить?
2) гит игнор я изменил как вы рекомендовали, но в репозитории и в первом дз остались  .DS_files нужно ли их удалить?

 p.s. табы пофиксил:)

2020-11-02 06:32 UTC, GkFoxes commented
Почему ты меня поставил на ревью? Это ДЗ первого блока, следовательно надо ставить Игоря!

Советую удалить все  .DS файлы

2020-11-06 16:38 UTC, korshunigor requested changes
Замечаний не много, хорошо!
По поводу вопроса падений при добавлении в обычный массив, все верно, это была демонстрация того, зачем мы делаем потокобезопасный массив, теперь потестив и узнав его проблему, можно его удалить )

А по поводу gitignore, он был добавлен до того как была создана ветка с ДЗ №2? Если да, то сделай сюда git pull origin develop, это притянет его в эту ветку, после чего можно будет удалить все .DS_Store файлы (если они сами не уберутся из git-а)

2020-11-06 16:38 UTC, korshunigor commented on HomeWork_2/HomeWork_2/ThreadSafeArray.swift
> +		items = []
Можно опустить, т.к. выше мы проинициализировали массив

2020-11-06 16:38 UTC, korshunigor commented on HomeWork_2/HomeWork_2/ThreadSafeArray.swift
> +		queue.sync(flags: .barrier) {
А нужен ли нам барьер, когда мы не изменяем данные?)

2020-11-06 16:39 UTC, korshunigor commented
И еще момент, желательно везде придерживаться одного стиля, где-то мы обращаемся к self явно, а где-то нет, желательно добавить это обращение везде, чтобы код выглядел более однородно.

2020-11-08 08:08 UTC, MaxFerrara commented
Привет) Насчет .gitignore, я его  добавил при создании репозитория ну как и должно быть, но потом при загрузке первого д/з у меня появились DS. файлы и примерно в тоже время Дима писал в чатик, что это нужно пофиксить. И по видео с твоей самой первой практики я это исправил.  Во втором дз у меня эти файлы уже не появились,  но те, что были остались и как я понял их можно будет удалить ручками?)

2020-11-09 17:38 UTC, korshunigor commented
> Привет) Насчет .gitignore, я его добавил при создании репозитория ну как и должно быть, но потом при загрузке первого д/з у меня появились DS. файлы и примерно в тоже время Дима писал в чатик, что это нужно пофиксить. И по видео с твоей самой первой практики я это исправил. Во втором дз у меня эти файлы уже не появились, но те, что были остались и как я понял их можно будет удалить ручками?)

Да, можно удалить их даже в самом GitHub-е если не ошибаюсь, либо открыв папку в Finder (вроде в режиме отображения скрытых файлов) и удалить их вручную )

2020-11-09 17:43 UTC, korshunigor commented
Сейчас посмотрел твой .gitignore файл в ветке develop, в ней нет исключения для .DS_Store, по этому они и продолжат добавляться, давай пофиксил это тут. Для этого открой .gitignore и дополни имеющиеся в нем правил теми что сгенерирует gitognore.io указав: "macOS", это еще одним коммитом в этой ветке бахни

2020-11-11 14:58 UTC, korshunigor approved these changes
Можно мержить

2020-11-12 02:31 UTC, merged